language: node_js
node_js:
  - node
cache: yarn
script:
  - yarn compile
  - yarn lint
  - yarn check-dependencies
  - yarn test
deploy:
  provider: script
  skip_cleanup: true
  script: bash -c 'echo $NPM_AUTH > ~/.npmrc && node scripts/nightly "$TRAVIS_COMMIT_RANGE"'
